import AuthWrapper from "@/components/AuthWrapper";
import { Suspense } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AuthWrapper>
            {children}
          </AuthWrapper>
        </Suspense>
      </body>
    </html>
  )
}